blank_issues_enabled: false
contact_links:
  - name: Questions or Discussion
    url: https://github.com/connorpmullins/warrant/discussions
    about: Ask questions or start a discussion instead of opening an issue.
